version: '3.5'

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  mongo_test_data:
    driver: local
  pgsql_test_data:
    driver: local
  vendor_data:
    driver: local

services:
  app:
    container_name: weather_app
    build:
      args:
        user: user
      context: ./
      dockerfile: .docker/Dockerfile
    tty: true
    networks:
      - app_network
    volumes:
      - .:/var/www

  nginx:
    image: nginx:alpine
    container_name: weather_nginx
    depends_on:
      - app
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - .docker/nginx:/etc/nginx/conf.d/
    networks:
      - app_network

  mongo:
    container_name: weather_mongodb
    image: mongo:latest
    tty: true
    depends_on:
      - app
    networks:
      - app_network
    ports:
      - ${DB_EXTERNAL_PORT_MONGO:-27017}:${DB_PORT}
    volumes:
      - mongo_data:/data/db

  mongo_test:
    container_name: weather_mongodb_test
    image: mongo:latest
    tty: true
    depends_on:
      - app
    networks:
      - app_network
    ports:
      - ${DB_EXTERNAL_PORT_MONGO_TEST:-27018}:${DB_PORT}
    volumes:
      - mongo_test_data:/data/db
