version: '3.5'

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  pgsql_test_data:
    driver: local
  vendor_data:
    driver: local

services:
  app:
    container_name: weather_app
    build:
      args:
        user: user
      context: ./
      dockerfile: .docker/Dockerfile
    depends_on:
      - database
      - database_test
    tty: true
    networks:
      - app_network
    volumes:
      - .:/var/www
#      - .docker/php:/var/www/docker-php-entrypoint

  nginx:
    image: nginx:alpine
    container_name: weather_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - .docker/nginx:/etc/nginx/conf.d/
    networks:
      - app_network

  mongo:
    container_name: weather_mongodb
    image: mongo:latest
    tty: true
    networks:
      - app_network
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${DB_MONGO_USERNAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${DB_MONGO_PASSWORD}
    ports:
      - ${DB_EXTERNAL_PORT_MONGO:-27017}:${DB_PORT}
    volumes:
      - mongo_data:/data/db

  database_test:
    container_name: weather_app_db_test
    image: postgres:latest
    tty: true
    networks:
      - app_network
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - "5435:5432"
    volumes:
      - pgsql_test_data:/var/lib/mysql
