#!/bin/sh

####################---Install Composer---####################
composer install -vvv --no-cache --no-interaction

php artisan migrate

echo '###---Running tests ...'
php artisan test --parallel

php-fpm
